
# tap repositories and their packages

tap 'homebrew/core'
brew 'aom'
brew 'autoconf'
brew 'c-ares'
brew 'cairo'
brew 'carthage'
brew 'cask'
brew 'curl'
brew 'emacs'
brew 'ffmpeg'
brew 'fish'
brew 'flac'
brew 'fontconfig'
brew 'freetype'
brew 'frei0r'
brew 'fribidi'
brew 'gdbm'
brew 'gettext'
brew 'gflags'
brew 'giflib'
brew 'gist'
brew 'git'
brew 'git-flow'
brew 'glib'
brew 'gmp'
brew 'gnutls'
brew 'graphite2'
brew 'grpc'
brew 'harfbuzz'
brew 'icu4c'
brew 'jpeg'
brew 'lame'
brew 'leptonica'
brew 'libass'
brew 'libbluray'
brew 'libevent'
brew 'libffi'
brew 'libidn2'
brew 'libogg'
brew 'libpng'
brew 'libsamplerate'
brew 'libsndfile'
brew 'libsoxr'
brew 'libtasn1'
brew 'libtiff'
brew 'libunistring'
brew 'libvidstab'
brew 'libvorbis'
brew 'libvpx'
brew 'little-cms2'
brew 'lzo'
brew 'mas'
brew 'mysql-client'
brew 'ncurses'
brew 'nettle'
brew 'node'
brew 'node-build'
brew 'nodebrew'
brew 'nodenv'
brew 'opencore-amr'
brew 'openjpeg'
brew 'openssl'
brew 'openssl@1.1'
brew 'opus'
brew 'p11-kit'
brew 'pcre'
brew 'pcre2'
brew 'pixman'
brew 'pkg-config'
brew 'protobuf'
brew 'python'
brew 'python@2'
brew 'rbenv'
brew 'rbenv-gemset'
brew 'readline'
brew 'rtmpdump'
brew 'rubberband'
brew 'ruby-build'
brew 'sdl2'
brew 'snappy'
brew 'sourcery'
brew 'speex'
brew 'sqlite'
brew 'swiftlint'
brew 'tesseract'
brew 'theora'
brew 'tree'
brew 'unbound'
brew 'webp'
brew 'wget'
brew 'x264'
brew 'x265'
brew 'xcodegen'
brew 'xvid'
brew 'xz'
brew 'yarn'
brew 'zsh'

tap 'homebrew/bundle'

tap 'homebrew/cask-versions'
cask 'adoptopenjdk8'

tap 'homebrew/services'

tap 'homebrew/cask'
cask '1password'
cask 'bloomrpc'
cask 'cyberduck'
cask 'docker'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'inkdrop'
cask 'karabiner-elements'
cask 'realm-studio'
cask 'skype'
cask 'sourcetree'
cask 'visual-studio-code'
cask 'xmind'

tap 'caskroom/cask'
cask 'alfred'
cask 'discord'
cask 'google-drive-file-stream'
cask 'java'
cask 'sketch'
cask 'tunnelblick'

tap 'dart-lang/dart'
brew 'dart'

tap 'mas-cli/tap'

tap 'mongodb/brew'
brew 'mongodb-community'

tap 'peripheryapp/periphery'
cask 'periphery'

tap 'rcmdnk/file'
brew 'brew-file'

tap 'spectralkh/tap'
cask 'flutter'

# Other Cask applications
cask 'caffeine'
cask 'hyper'
cask 'mysqlworkbench'
cask 'slack'
cask 'vlc'

# App Store applications
mas 'Amphetamine', id: 937984704
mas 'Be_Focused', id: 973134470
mas 'DevCleaner', id: 1388020431
mas 'Gifski', id: 1351639930
mas 'iMovie', id: 408981434
mas 'Keynote', id: 409183694
mas 'LINE', id: 539883307
mas 'Paste', id: 967805235
mas 'PiPifier', id: 1160374471
mas 'Realm_Browser', id: 1007457278
mas 'TweetDeck', id: 485812721
mas 'Xcode', id: 497799835
mas 'Yoink', id: 457622435
mas 'ライトクリーナー', id: 1037994372
